config/routes.rb
CityCenter::Application.routes.draw do

  devise_for :users

  root :to => "home#index"

  resources :organizations do
    resources :events
  end

  resources :events, only: [:index]

  resources :attendees

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :organization
  has_many :attendees, :dependent => :destroy
  has_many :users, :through => :attendees

  attr_accessible :name, :description, :venue, :scheduled_on, :starts_at, :ends_at, :organization_id, :organizer, :contact_email
  # validates :name, :description, :scheduled_on, :starts_at, :ends_at, :presence => true
  validates_presence_of :name, :scheduled_on, :venue, :starts_at, :ends_at

  def parent_organization
    Organization.where(:id => self.organization_id).first
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!

  def index

    if params[:organization_id]
      @organization = load_organization
      @events = @organization.events.all
      @events_by_date = @events.group_by(&:scheduled_on)
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
    else
      @events = Event.all
      @organization = Organization.all
      @events_by_date = @events.group_by(&:scheduled_on)
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
    end

  end

  def new
    @organization = load_organization
    unless @organization
      flash[:notice] = "Only organizations can create events. Please create an organization first."
      redirect_to root_path
    end
    @event = Event.new
  end

  def create
    @organization = Organization.where(:id => params[:organization_id]).first

    unless @organization
      flash[:notice] = "Only organizations can create events. Please create an organization first."
      redirect_to new_organization_path
    end

    if params[:event][:ends_at].blank?
      @event = @organization.events.new(params[:event])
    else
      @event = @organization.events.new(params[:event])
    end

    if @event.save
      flash.notice = "Your event has been created"
      @event = Event.where(params[:event]).first
      redirect_to organization_event_path(@organization, @event)
    else
      flash.now.notice = "Your event could not be created, please try again."
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @organization = Organization.where(:id => params[:organization_id]).first
    @attendees = Attendee.where(:event_id => @event.id)
  end

  def edit
    @organization = load_organization
    if @organization
      @events = @organization.events.all
      @event = @organization.events.where(:id => params[:id]).first
    else
      flash[:notice] = "Only authorized organizations can edit events."
      redirect_to new_organization_path
    end
  end

  def update
    @organization = load_organization
    if @organization
      @event = Event.find(params[:id])
      @event.update_attributes(params[:event])
      redirect_to organization_event_path(@organization, @event)
    else
      flash[:notice] = "Only authorized organizations can update events."
      redirect_to new_organization_path
    end
  end

  def destroy
    @organization = load_organization
    if @organization
      @event = Event.find(params[:id])
      @event.destroy
      flash[:notice] = "Your event has been deleted"
      redirect_to organization_path(@organization)
    else
      flash[:notice] = "Only authorized organizations can delete events."
      redirect_to root_path
    end
  end

  def load_organization
    Organization.where(:user_id => current_user.id, :id => params[:organization_id]).first
  end
end

app/views/events/edit.html.erb
<div class="event-form row-fluid">


<div class="span3">
  <h2>Edit Event </h3>
</div>

<div class="span4">
<%= form_for [@organization, @event] do |f| %>

  <div><%= f.label :name %>
  <%= f.text_field :name, :autofocus => true %></div>

  <div><%= f.label :description %>
  <%= f.text_area :description, :cols => 10, :rows => 10 %></div>
</div>

<div class="span5">
  <%= f.label :venue %>
  <%= f.text_field :venue %>

  <%= f.label :scheduled_on %>
  <%= f.text_field :scheduled_on %>

  <%= f.label :starts_at %>
  <%= f.text_field :starts_at %>

  <%= f.label :ends_at %>
  <%= f.text_field :ends_at %>

  <%= f.submit "Update Event", :class => "form-submit-btn" %>
<% end %>

</div>

app/views/events/index.html.erb
<div class="full_calendar row-fluid">


  <div class="span12">
    <div id="events">
      <h2 id="month">
        <%= link_to "<", date: @date.prev_month %>
        <%= @date.strftime("%B %Y") %>
        <%= link_to ">", date: @date.next_month %>
      </h2>
       <p class="add-event-link"> <% if current_user.organizations.count > 1 %>
        <!-- Button to trigger modal -->
          <a href="#eventModal" class="capitalized" role="button" data-toggle="modal">Add Event</a>

        <% elsif current_user.organizations.count == 1  %>
          <%= link_to "Add Event", new_organization_event_path(current_user.organizations.first), :class => "capitalized" %>
        <% else %>
        </p>
        <% end %>
      <%= calendar @date do |date| %>
        <%= date.day %>
        <% if @events_by_date[date] %>
          <ul>
            <% @events_by_date[date].each do |event| %>
              <li><%= link_to event.name, organization_event_path(@organization.find(:id => event.organization_id).first, event) %></li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<!-- Modal -->
<div id="eventModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="eventModallLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Select the organization you'd like to <br/>create an event for.</h3>
  </div>
  <div class="modal-body">
    <% current_user.organizations.each do |organization| %></p>
          <div class="span2">
            <%= link_to new_organization_event_path(organization) do %>
                <%= image_tag organization.avatar_url(:event), :class => "organization-image" %>
            <% end %>
            <h4 class="title">
              <%= organization.name %>
            </h4>
          </div>

        <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="event-form row-fluid">

<div class="span3">
<h2>New Event</h2>
<p class="capitalized align-center">for <%= @organization.name %></p>
</div>

<div class="span4">
  <% @event.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>

  <%= form_for [@organization, @event] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_area :description, :cols => 10, :rows => 10 %>
</div>

<div class="span5 event-form2">
    <%= f.label :venue %>
    <%= f.text_field :venue %>

    <%= f.label :scheduled_on %>
    <%= f.text_field :scheduled_on, :placeholder => "YYYY-MM-DD" %>

    <%= f.label :starts_at %>
    <%= f.text_field :starts_at, :placeholder => "6:00PM"%>

    <%= f.label :ends_at %>
    <%= f.text_field :ends_at, :placeholder => "7:00PM" %>

    <%= f.submit "Create Event", :class => "form-submit-btn" %>
<% end %>

</div>
</div>

app/views/events/show.html.erb
<div class="event-detail row-fluid">
  <div class="span12 event-card">
   <h3> <%= @event.name %></h3><span class="capitalized"> Hosted by:  <%= link_to @organization.name, organization_path(@organization)%></span></p>
    <p class="event-info">Date: <%= @event.scheduled_on.strftime("%m-%d-%Y")%>  |  Location: <%= @event.venue %>  |  Time: <%= @event.starts_at.strftime("%I:%M%p") %> <% if @event.ends_at %>
        <%= @event.ends_at.strftime("to %I:%M%p") %>
      <% end %></p>


    <p class="description"><%= @event.description if @event.description != ""%></p>

    <div class="event-attendees">
        <h4>Attendees:</h4>
          <ul>
            <% @attendees.each do |attendee| %>
              <li><%= image_tag attendee.user.avatar_url(:thumb) %></li>
            <% end %>
          </ul>
    </div>

<div class="row-fluid footer">
    <div class="manage_event_links span6">
      <%  if current_user.id == @organization.user_id %>
        <%= link_to("Edit Event |  ", edit_organization_event_path(@organization, @event)) %>
        <%= link_to("Delete Event", organization_event_path(@organization, @event), :method => :delete, :confirm => "Are you sure you want to delete #{@event.name}?")%>
      <% end %>
    </div>

    <div class="manage_event_links span4 offset2">
    <% if current_user.is_attending?(@event) %>
      <%= link_to("Leave Event", attendee_path(@event), :method => :delete, :id => "attend_btn")%>
    <% else %>
      <%= link_to("Attend Event", attendees_path(@event), :params => { :event_id => @event.id, :user_id => current_user.id }, :method => :create, :id => "attend_btn") %>
    <% end %>
  </div>

  </div>
</div>