config/routes.rb
CityCenter::Application.routes.draw do

  devise_for :users

  root :to => "home#index"

  resources :organizations do
    resources :events
  end

  resources :events, only: [:index]

  resources :attendees

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :user
  has_many :events


  validates_presence_of :name

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :bio, :mission, :city, :state, :zip, :contact_email, :website, :twitter_handle, :facebook, :youtube, :logo, :avatar, :remote_avatar_url, :avatar_cache
  # attr_accessible :title, :body

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = current_user.organizations.create(params[:organization])

    if @organization.persisted?
      flash.notice = "Your organization has been created"
      redirect_to organization_path(@organization)
    else
      flash.notice = "Your organization could not be created"
      render :new
    end
  end

  def show
    @organization = Organization.find(params[:id])
    @events = @organization.events.all
  end

  def edit
    @organization = load_organization
    unless @organization
      flash[:notice] = "You are not permitted to edit this organization"
      redirect_to root_path
    end
  end

  def update
    @organization = load_organization
    if @organization
      @organization.update_attributes(params[:organization])
      redirect_to organization_path
    else
      flash[:notice] = "You are not permitted to update this organization"
      redirect_to root_path
    end
  end

  def destroy
    @organization = load_organization
    unless @organization
      flash[:notice] = "You are not permitted to delete this organization"
      redirect_to root_path
    end
    @organization.events.each do |event|
      event.delete
    end

    @organization.delete
    flash[:notice] = "Your organization has been deleted."
    redirect_to root_path
  end

  private

  def load_organization
    Organization.where(:user_id => current_user.id, :id => params[:id]).first
  end
end

app/views/organizations/edit.html.erb
<div class="organization-form row-fluid">

<div class="span3">
  <h2> Edit Organization </h2>
</div>

<div class="span4">
<%= form_for(@organization) do |f| %>

  <div><%= f.label :name %>
  <%= f.text_field :name, :autofocus => true %></div>

  <p>
    <%= image_tag @organization.avatar_url(:thumb) if @organization.avatar? %>
    <label>Profile Picture</label>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache %>
  </p>

  <%= f.label :bio %>
  <%= f.text_area :bio, :cols => 10, :rows => 10 %>
</div>

  <div class="span5">
    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :state %>
    <%= f.text_field :state %>

    <%= f.label :contact_email %>
    <%= f.text_field :contact_email %>

    <%= f.label :website %>
    <%= f.text_field :website %>

    <%= f.label :facebook %>
    <%= f.text_field :facebook %>

    <%= f.label :twitter_handle %>
    <%= f.text_field :twitter_handle%>

    <%= f.label :youtube %>
    <%= f.text_field :youtube %>

    <div><%= f.submit "Edit Profile", :class => "form-submit-btn" %></div>
  <% end %>
  </div>
</div>

app/views/organizations/new.html.erb
<div class="organization-form row-fluid">

  <div class="span3">
    <h2>New Organization</h2>
    <% @organization.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>

  <div class="span4">
  <%= form_for @organization, :html => {:multipart => true} do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <p>
      <%= image_tag @organization.avatar_url(:thumb) if @organization.avatar? %>
      <label>Profile Picture</label>
      <%= f.file_field :avatar %>
      <%= f.hidden_field :avatar_cache %>
    </p>
      <%= f.label :bio %>
      <%= f.text_area :bio, :cols => 10, :rows => 10 %>
  </div>

  <div class="span5">

      <%= f.label :city %>
      <%= f.text_field :city %>

      <%= f.label :state %>
      <%= f.text_field :state %>

      <%= f.label :contact_email %>
      <%= f.text_field :contact_email %>

      <%= f.label :website %>
      <%= f.text_field :website %>

      <%= f.label :facebook %>
      <%= f.text_field :facebook %>

      <%= f.label :twitter_handle %>
      <%= f.text_field :twitter_handle%>

      <%= f.label :youtube %>
      <%= f.text_field :youtube %>

      <%= f.submit "Create Organization", :class => "form-submit-btn" %>
    <% end %>
  </div>
</div>

app/views/organizations/show.html.erb
<div class="organization-dashboard row-fluid">

<div class="organization-panel span4">
  <h2><%= @organization.name %></h2>
  <% if @organization.bio != "" %>
    <p><%= @organization.bio %></p>
  <% end %>
  <ul>
    <% if @organization.city != "" && @organization.state != "" %>
      <span><%= @organization.city %>, <%= @organization.state %></span><br/>
    <% end %>

    <% if @organization.contact_email != ""  %>
      <span><%= @organization.contact_email %></span><br/>
    <% end %>

    <% if @organization.contact_email != "" %>
      <span><%= @organization.website %></span><br/>
    <% end %>

    <% if @organization.facebook != "" %>
      <span><%= @organization.facebook %></span><br/>
    <% end %>

    <% if @organization.twitter_handle != "" %>
      <span><%= @organization.twitter_handle %></span><br/>
    <% end %>

    <% if @organization.youtube != ""  %>
      <span><%= @organization.youtube %></span><br/>
    <% end %>

  </ul>

  <% if current_user.id == @organization.user_id %>

  <div class="manage_links">
      <%= link_to("Edit Profile  ", edit_organization_path(@organization)) %> |

      <%= link_to("  Delete Organization", organization_path(@organization), :method => :delete, :confirm => "Are you sure you want to delete #{@organization.name}?")%>
  </div>

  <div class="add_event_link">
    <%= link_to "Add Event", new_organization_event_path(@organization), :class => "add-event" %>
  </div>
  <% end %>

</div>

<div class="events span8">
    <% if @organization.events.count > 0 %>
      <div class="row-fluid">
        <% @organization.events[0..2].each do |event| %>
          <div class="event span4">
                <h2 class="event-date-box-large"><%= event.scheduled_on.strftime("%m-%d") %></h2><br/>
            <%= link_to event.name, organization_event_path(@organization, event) %><br/>
             <%= link_to "view details", organization_event_path(@organization, event), :class => "capitalized" %>
          </div>
        <% end %>
      <% if @organization.events.count > 3 %>
        </div>
        <br/>
      <div class="row-fluid">
        <% @organization.events[3..5].each do |event| %>
          <div class="event span4">
                <h2 class="event-date-box-large"><%= event.scheduled_on.strftime("%m-%d") %></h2><br/>
            <%= link_to event.name, organization_event_path(@organization, event) %><br/>
             <%= link_to "view details", organization_event_path(@organization, event), :class => "capitalized" %>
          </div>
        <% end %>
      </div>
       <% end %>
    <% else %>

      <% if current_user.id == @organization.user_id %>
        <p> You currently have no upcoming events, please create one <%= link_to " here.", new_organization_event_path(@organization), :class => "current-user" %><p>
      <% else %>
        <p> This organization currently has no upcoming events. Please check back soon. </p>
      <% end %>
    <% end %>
  </ul>
</div>